// API không có endpoint /cities, nhưng `GET /jobs` lại lọc theo `city_id` và
// `POST /employer/jobs` nhận `work_location[].city_id`. Danh sách này là nguồn
// duy nhất cho cả hai phía: tin đăng lưu `city_id` lấy từ đây, bộ lọc cũng gửi
// `city_id` lấy từ đây — chỉ cần nhất quán nội bộ là filter chạy đúng.
// Mã tỉnh theo Tổng cục Thống kê.
export const CITIES = [
    { id: 1, name: "Hà Nội" },
    { id: 79, name: "Hồ Chí Minh" },
    { id: 48, name: "Đà Nẵng" },
    { id: 89, name: "An Giang" },
    { id: 77, name: "Bà Rịa - Vũng Tàu" },
    { id: 95, name: "Bạc Liêu" },
    { id: 24, name: "Bắc Giang" },
    { id: 6, name: "Bắc Kạn" },
    { id: 27, name: "Bắc Ninh" },
    { id: 83, name: "Bến Tre" },
    { id: 52, name: "Bình Định" },
    { id: 74, name: "Bình Dương" },
    { id: 70, name: "Bình Phước" },
    { id: 60, name: "Bình Thuận" },
    { id: 96, name: "Cà Mau" },
    { id: 92, name: "Cần Thơ" },
    { id: 4, name: "Cao Bằng" },
    { id: 66, name: "Đắk Lắk" },
    { id: 67, name: "Đắk Nông" },
    { id: 11, name: "Điện Biên" },
    { id: 75, name: "Đồng Nai" },
    { id: 87, name: "Đồng Tháp" },
    { id: 64, name: "Gia Lai" },
    { id: 2, name: "Hà Giang" },
    { id: 35, name: "Hà Nam" },
    { id: 42, name: "Hà Tĩnh" },
    { id: 30, name: "Hải Dương" },
    { id: 31, name: "Hải Phòng" },
    { id: 93, name: "Hậu Giang" },
    { id: 17, name: "Hoà Bình" },
    { id: 33, name: "Hưng Yên" },
    { id: 56, name: "Khánh Hòa" },
    { id: 91, name: "Kiên Giang" },
    { id: 62, name: "Kon Tum" },
    { id: 12, name: "Lai Châu" },
    { id: 68, name: "Lâm Đồng" },
    { id: 20, name: "Lạng Sơn" },
    { id: 10, name: "Lào Cai" },
    { id: 80, name: "Long An" },
    { id: 36, name: "Nam Định" },
    { id: 40, name: "Nghệ An" },
    { id: 37, name: "Ninh Bình" },
    { id: 58, name: "Ninh Thuận" },
    { id: 25, name: "Phú Thọ" },
    { id: 54, name: "Phú Yên" },
    { id: 44, name: "Quảng Bình" },
    { id: 49, name: "Quảng Nam" },
    { id: 51, name: "Quảng Ngãi" },
    { id: 22, name: "Quảng Ninh" },
    { id: 45, name: "Quảng Trị" },
    { id: 94, name: "Sóc Trăng" },
    { id: 14, name: "Sơn La" },
    { id: 72, name: "Tây Ninh" },
    { id: 34, name: "Thái Bình" },
    { id: 19, name: "Thái Nguyên" },
    { id: 38, name: "Thanh Hóa" },
    { id: 46, name: "Thừa Thiên Huế" },
    { id: 82, name: "Tiền Giang" },
    { id: 84, name: "Trà Vinh" },
    { id: 8, name: "Tuyên Quang" },
    { id: 86, name: "Vĩnh Long" },
    { id: 26, name: "Vĩnh Phúc" },
    { id: 15, name: "Yên Bái" },
];

export function findCityById(id) {
    const numericId = Number(id);
    return CITIES.find((city) => city.id === numericId) ?? null;
}
